#------------------------------------------------------------------------------------
# primaryGeneratorSetup.mac: Set up the primary generator environment
#  [Note] Geant4 Tutorial for Hep/Medicine Users
#------------------------------------------------------------------------------------

## In 'P07_PrimaryGenerator:MyGen' you cannot use primaryGeneratorSetup.mac.
## Therefore this file has just this comment.
